In [15]:
import numpy as np

In [31]:
a = np.array([1, 2, 3, 4, 5]) #declaring an array using list anotation

a

array([1, 2, 3, 4, 5])

In [35]:
b = np.array((6, 7, 8, 9, 10)) #declaring an array using tuple anotation

b

array([ 6,  7,  8,  9, 10])

In [24]:
#different mathematical operations can be perfomed on numpy array, which which reflect on each element of the array.

a * 3 

array([ 3,  6,  9, 12, 15])

In [47]:
# mathematical operations between two arrays

a + b

array([ 7,  9, 11, 13, 15])

In [48]:
b / a

array([ 6.        ,  3.5       ,  2.66666667,  2.25      ,  2.        ])

In [20]:
type(a)

numpy.ndarray

In [21]:
a.dtype

dtype('int32')

In [27]:
#bytes per element

a.itemsize 

4

In [30]:
#size reports total number of elements in an Array.

a.size 

5

In [33]:
a.shape #it indicates that array has 5 elements along dimension zero in this case.

(5,)

In [42]:
c = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
#number of rows and columns

c.shape 

(2, 5)

In [45]:
len(c)

2

In [46]:
c.size

10

In [49]:
# Return the number of bytes used by the data portion of the array

c.nbytes

40

In [50]:
# number od dimensions

c.ndim

2

In [51]:
# Array Indexing
a

array([1, 2, 3, 4, 5])

In [52]:
a[0]

1

In [53]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [54]:
c[1][2]

8

In [55]:
# Re-assigning values

a[0] = 50

In [56]:
a

array([50,  2,  3,  4,  5])

In [57]:
# set all values in an array using Fill

a.fill(0)

In [58]:
a

array([0, 0, 0, 0, 0])

In [59]:
#this also works but can be slower

a[:] = 100

In [60]:
a

array([100, 100, 100, 100, 100])

In [61]:
# assigning a float into an int32 array truncates the decimal part

a[0] = 5.8

In [62]:
a

array([  5, 100, 100, 100, 100])

In [63]:
# fill has the same behaviour

a.fill(4.6)

In [64]:
a

array([4, 4, 4, 4, 4])

In [66]:
# Slicing for Arrays works like List Slicing

b

array([ 6,  7,  8,  9, 10])

In [67]:
b[2:4]

array([8, 9])

In [68]:
b[-4:3]

array([7, 8])

In [69]:
b[::2]

array([ 6,  8, 10])

In [71]:
# Creating array using arange

np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [76]:
r = np.arange(30).reshape(5,6)

In [75]:
r 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [77]:
r[-1, -1] # Unlike list, multiple parameters can be passed in single bracket to locate an element in the array. 

29

In [87]:
r[1, 1]

7

In [88]:
r[2, 1:]

array([13, 14, 15, 16, 17])

In [89]:
r[:1 , :1]

array([[0]])

In [90]:
r[: , 2] = 100 #targeting a column

In [91]:
r

array([[  0,   1, 100,   3,   4,   5],
       [  6,   7, 100,   9,  10,  11],
       [ 12,  13, 100,  15,  16,  17],
       [ 18,  19, 100,  21,  22,  23],
       [ 24,  25, 100,  27,  28,  29]])

In [83]:
list_example = [[1,2,3], [4,5,6]]

In [84]:
list_example[-1][-1] # here we have to passmeters in separate brackets

6

In [92]:
r % 3 == 0 # values divisible by 3

array([[ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False]], dtype=bool)

In [93]:
r[r % 3 == 0] # Using above mask/condition to get the values.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [98]:
b

array([ 6,  7,  8,  9, 10])

In [99]:
b.sum()

40

In [100]:
b.prod()

30240

In [101]:
b.mean()

8.0

In [102]:
b.max()

10

In [103]:
b.min()

6

In [108]:
r

array([[  0,   1, 100,   3,   4,   5],
       [  6,   7, 100,   9,  10,  11],
       [ 12,  13, 100,  15,  16,  17],
       [ 18,  19, 100,  21,  22,  23],
       [ 24,  25, 100,  27,  28,  29]])

In [109]:
r[2, 4]  = -10

In [110]:
r

array([[  0,   1, 100,   3,   4,   5],
       [  6,   7, 100,   9,  10,  11],
       [ 12,  13, 100,  15, -10,  17],
       [ 18,  19, 100,  21,  22,  23],
       [ 24,  25, 100,  27,  28,  29]])

In [111]:
np.unravel_index(r.argmin(), r.shape) #to find the index of min/smallest element in the array

(2, 4)

In [113]:
# different options to create arrays
# reshape function can be used with these options to give array a desired shape

np.arange(5)

array([0, 1, 2, 3, 4])

In [114]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [115]:
np.ones(6)

array([ 1.,  1.,  1.,  1.,  1.,  1.])

In [117]:
np.linspace(0, 2, 10) #similar to arange

array([ 0.        ,  0.22222222,  0.44444444,  0.66666667,  0.88888889,
        1.11111111,  1.33333333,  1.55555556,  1.77777778,  2.        ])